/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GlobeRouteImport } from './routes/globe'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SeaLifeRouteImport } from './routes/sea-life'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as OceanOceanIdIndexRouteImport } from './routes/ocean.$oceanId.index'
import { Route as OceanOceanIdMatchRouteImport } from './routes/ocean.$oceanId.match'
import { Route as OceanOceanIdLevelLevelIdRouteImport } from './routes/ocean.$oceanId.level.$levelId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobeRoute = GlobeRouteImport.update({
  id: '/globe',
  path: '/globe',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SeaLifeRoute = SeaLifeRouteImport.update({
  id: '/sea-life',
  path: '/sea-life',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const OceanOceanIdIndexRoute = OceanOceanIdIndexRouteImport.update({
  id: '/ocean/$oceanId/',
  path: '/ocean/$oceanId/',
  getParentRoute: () => rootRouteImport,
} as any)
const OceanOceanIdMatchRoute = OceanOceanIdMatchRouteImport.update({
  id: '/ocean/$oceanId/match',
  path: '/ocean/$oceanId/match',
  getParentRoute: () => rootRouteImport,
} as any)
const OceanOceanIdLevelLevelIdRoute =
  OceanOceanIdLevelLevelIdRouteImport.update({
    id: '/ocean/$oceanId/level/$levelId',
    path: '/ocean/$oceanId/level/$levelId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/globe': typeof GlobeRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/sea-life': typeof SeaLifeRoute
  '/shop': typeof ShopRoute
  '/ocean/$oceanId/match': typeof OceanOceanIdMatchRoute
  '/ocean/$oceanId/': typeof OceanOceanIdIndexRoute
  '/ocean/$oceanId/level/$levelId': typeof OceanOceanIdLevelLevelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/globe': typeof GlobeRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/sea-life': typeof SeaLifeRoute
  '/shop': typeof ShopRoute
  '/ocean/$oceanId/match': typeof OceanOceanIdMatchRoute
  '/ocean/$oceanId': typeof OceanOceanIdIndexRoute
  '/ocean/$oceanId/level/$levelId': typeof OceanOceanIdLevelLevelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/globe': typeof GlobeRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/sea-life': typeof SeaLifeRoute
  '/shop': typeof ShopRoute
  '/ocean/$oceanId/match': typeof OceanOceanIdMatchRoute
  '/ocean/$oceanId/': typeof OceanOceanIdIndexRoute
  '/ocean/$oceanId/level/$levelId': typeof OceanOceanIdLevelLevelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/globe'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/sea-life'
    | '/shop'
    | '/ocean/$oceanId/match'
    | '/ocean/$oceanId/'
    | '/ocean/$oceanId/level/$levelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/globe'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/sea-life'
    | '/shop'
    | '/ocean/$oceanId/match'
    | '/ocean/$oceanId'
    | '/ocean/$oceanId/level/$levelId'
  id:
    | '__root__'
    | '/'
    | '/globe'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/sea-life'
    | '/shop'
    | '/ocean/$oceanId/match'
    | '/ocean/$oceanId/'
    | '/ocean/$oceanId/level/$levelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GlobeRoute: typeof GlobeRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
  SeaLifeRoute: typeof SeaLifeRoute
  ShopRoute: typeof ShopRoute
  OceanOceanIdMatchRoute: typeof OceanOceanIdMatchRoute
  OceanOceanIdIndexRoute: typeof OceanOceanIdIndexRoute
  OceanOceanIdLevelLevelIdRoute: typeof OceanOceanIdLevelLevelIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/globe': {
      id: '/globe'
      path: '/globe'
      fullPath: '/globe'
      preLoaderRoute: typeof GlobeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sea-life': {
      id: '/sea-life'
      path: '/sea-life'
      fullPath: '/sea-life'
      preLoaderRoute: typeof SeaLifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ocean/$oceanId/': {
      id: '/ocean/$oceanId/'
      path: '/ocean/$oceanId'
      fullPath: '/ocean/$oceanId/'
      preLoaderRoute: typeof OceanOceanIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ocean/$oceanId/match': {
      id: '/ocean/$oceanId/match'
      path: '/ocean/$oceanId/match'
      fullPath: '/ocean/$oceanId/match'
      preLoaderRoute: typeof OceanOceanIdMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ocean/$oceanId/level/$levelId': {
      id: '/ocean/$oceanId/level/$levelId'
      path: '/ocean/$oceanId/level/$levelId'
      fullPath: '/ocean/$oceanId/level/$levelId'
      preLoaderRoute: typeof OceanOceanIdLevelLevelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GlobeRoute: GlobeRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
  SeaLifeRoute: SeaLifeRoute,
  ShopRoute: ShopRoute,
  OceanOceanIdMatchRoute: OceanOceanIdMatchRoute,
  OceanOceanIdIndexRoute: OceanOceanIdIndexRoute,
  OceanOceanIdLevelLevelIdRoute: OceanOceanIdLevelLevelIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
